version: '3'

services:
  # Main django backend
  django:
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./local.env # Your .env here
    volumes:
      - ./bard_app_api:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  # Nginx
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  # Celery
  celery-beat:
    build:
      dockerfile: Dockerfile
    command: celery --app=lol_stats_api.celeryApp beat --loglevel=info
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  celery-worker:
    build:
      dockerfile: Dockerfile
    command: celery --app=lol_stats_api.celeryApp worker -B -l INFO --concurrency=6
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 


  # Process matchlist
  process-matchlist:
    build:
      dockerfile: Dockerfile
    command: python manage.py process_matches
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  # Process servers matchlists
  process-matchlist-br:
    build:
      dockerfile: Dockerfile
    command: python manage.py process_matchlist BR
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  process-matchlist-eun:
    build:
      dockerfile: Dockerfile
    command: python manage.py process_matchlist EUN
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  process-matchlist-euw:
    build:
      dockerfile: Dockerfile
    command: python manage.py process_matchlist EUW
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  process-matchlist-jp:
    build:
      dockerfile: Dockerfile
    command: python manage.py process_matchlist JP
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  process-matchlist-kr:
    build:
      dockerfile: Dockerfile
    command: python manage.py process_matchlist KR
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  process-matchlist-lan:
    build:
      dockerfile: Dockerfile
    command: python manage.py process_matchlist LAN
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  process-matchlist-las:
    build:
      dockerfile: Dockerfile
    command: python manage.py process_matchlist LAS
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  process-matchlist-na:
    build:
      dockerfile: Dockerfile
    command: python manage.py process_matchlist NA
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  process-matchlist-oc:
    build:
      dockerfile: Dockerfile
    command: python manage.py process_matchlist OC
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  process-matchlist-ru:
    build:
      dockerfile: Dockerfile
    command: python manage.py process_matchlist RU
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 

  process-matchlist-tr:
    build:
      dockerfile: Dockerfile
    command: python manage.py process_matchlist TR
    env_file:
      - ./local.env # Your .env here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # The maximum size of the log before it is rolled. A positive integer plus a modifier representing the unit of measure (k, m, or g).
        max-file: "10" 