# Generated by Django 3.0.7 on 2020-08-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20200823_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champplaystyle',
            name='gameId',
            field=models.BigIntegerField(),
        ),
    ]
