# Generated by Django 3.0.7 on 2020-08-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='puuid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
