# Generated by Django 3.0.7 on 2020-08-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20200823_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillup',
            name='_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_10',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_11',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_12',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_13',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_14',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_15',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_16',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_17',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_18',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_6',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_7',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_8',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skillup',
            name='_9',
            field=models.IntegerField(null=True),
        ),
    ]
